name: WaitPlugin
version: '${project.version}'
main: fr.youtee.waitplugin.WaitPlugin
api-version: '1.20'

commands:
  wait:
    description: Commande pour la temporisation.
    usage: /wait <seconds> <commands>